# Generated by Django 2.2 on 2019-05-06 05:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0002_healthinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Formato inválido', regex='^\\+?1?\\d{9,15}$')])),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plans', models.ManyToManyField(related_name='clinics', through='clinics.ClinicInsurance', to='shared.HealthInsurance')),
                ('specialties', models.ManyToManyField(related_name='clinics', through='clinics.ClinicSpecialty', to='shared.Specialty')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.AddField(
            model_name='clinicspecialty',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.ClinicUser'),
        ),
        migrations.AddField(
            model_name='clinicspecialty',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.Specialty'),
        ),
        migrations.AddField(
            model_name='clinicinsurance',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.ClinicUser'),
        ),
        migrations.AddField(
            model_name='clinicinsurance',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.HealthInsurance'),
        ),
    ]
