# Generated by Django 2.2 on 2019-05-06 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Plano de saúde',
                'verbose_name_plural': 'Planos de saúde',
            },
        ),
    ]
